version: '3.8'

services:
  anpr-app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./plate_recognition/static/exports:/app/plate_recognition/static/exports
      - ./plate_recognition/uploads:/app/plate_recognition/uploads
      - ./runs:/app/runs
    environment:
      - FLASK_ENV=production
      - PYTHONPATH=/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
